#!/bin/bash

setp () {
    _PATH=$PROC/$1

    echo -ne "Setting up $_PATH to $2 ..."

    # Don't set anything if path doesn't exist
    [ -f $_PATH ] && {
        echo $2 > $_PATH
        echo "Ok"
    } || {
        echo "Failed"
    }

}

throw () {
    echo "Error: $2"
    exit $1
}
